### ISSUE TITLE
[Bug] Compilation Issue Regarding HDF5 and System Calls

### ISSUE THREAD

**Issue by jbuffaloe** [jfb3615/qat#3]
While compiling with the most recent commit, I ran into an issue with finding hdf5.h. Fixing this required fixing the system calls at [https://github.com/jfb3615/qat/blob/24dd61fc06ae72fd0bb82801c9db4a14615e9c79/Qhfd/src/qt.pro#L51-L54](url) to instead be:
```
else {
  LIBS           += $$system(pkg-config --libs   hdf5-openmpi) 
  QMAKE_CXXFLAGS += $$system(pkg-config --cflags hdf5-openmpi) 
}
```

**Comment by jfb3615** [comment]
Thanks Jesse I have implemented this fix. Best, --Joe Boudreau
